#! /bin/sh
### BEGIN INIT INFO
# Provides:		redis-cluster
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	redis-cluster - a cluster of Persistent key-value db
# Description:		redis-cluster - a cluster Persistent key-value db
### END INIT INFO

###########VARIABLES START########
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/redis-server
NAME=redis-cluster
DESC=redis-cluster
CONFDIR=/usr/local/etc/redis
PIDDIR=/var/run
NODENO=8
###########VARIABLES END##########
####conf files in the form "redis-node-1.conf, redis-node-2.conf...."

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
  i=0
  while [ $i != $NODENO ]; do
    i=`expr $i + 1`
    NODENAME="redis-node-$i"
    echo -n "Starting ${NODENAME}: "
    PIDFILE=${PIDDIR}/${NODENAME}.pid
    touch ${PIDFILE}
    chown redis:redis ${PIDFILE}
    if start-stop-daemon --start --quiet --umask 007 --pidfile ${PIDFILE} --chuid redis:redis --exec $DAEMON -- ${CONFDIR}/${NODENAME}.conf
    then
      echo "success."
    else
      echo "failed"
    fi
  done
	;;
  stop)
  i=0
  while [ $i != $NODENO ]; do
    i=`expr $i + 1`
    NODENAME="redis-node-$i"
    echo -n "Stopping ${NODENAME}: "
    PIDFILE=${PIDDIR}/${NODENAME}.pid
    if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile ${PIDFILE} --exec $DAEMON
    then
      echo "success."
    else
      echo "failed"
    fi
    rm -f ${PIDFILE}
  done
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
  i=0
  while [ $i != $NODENO ]; do
    i=`expr $i + 1`
    NODENAME="redis-node-$i"
    echo -n "${NODENAME} is "
    PIDFILE=${PIDDIR}/${NODENAME}.pid
    if start-stop-daemon --stop --quiet --signal 0 --name ${NODENAME} --pidfile ${PIDFILE}
    then
      echo "running"
    else
      echo "not running"
    fi
  done
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
